name: health
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.6


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  percent_indicator: ^3.0.1
  firebase_auth: ^1.3.0
  google_sign_in: ^5.0.4
  font_awesome_flutter: ^9.0.0
  provider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/loading.gif
     - assets/images/image001.jpg
     - assets/images/image002.jpg
     - assets/images/image003.jpg
     - assets/images/image004.jpg
     - assets/images/image005.jpg
     - assets/images/image006.jpg
     - assets/images/image007.jpg
     - assets/images/image008.jpg
     - assets/images/image009.jpg
     - assets/images/image010.jpg
     - assets/images/image011.jpg
     - assets/images/image012.jpg
     - assets/images/image013.jpg
     - assets/images/image014.jpeg
     - assets/images/image015.jpg
     - assets/images/Byoga1.jpeg
     - assets/images/Byoga2.jpeg
     - assets/images/Byoga3.jpeg
     - assets/images/Byoga4.jpeg
     - assets/images/Iyoga1.jpeg
     - assets/images/Iyoga2.jpeg
     - assets/images/Iyoga3.jpeg
     - assets/images/Iyoga4.jpeg
     - assets/images/Ayoga1.jpeg
     - assets/images/Ayoga2.jpeg
     - assets/images/Ayoga3.jpeg
     - assets/images/Ayoga4.jpeg
     - assets/images/Arm1.jpeg
     - assets/images/Arm2.jpeg
     - assets/images/Arm3.jpeg
     - assets/images/Arm4.jpeg
     - assets/images/Arm5.jpeg
     - assets/images/Arm6.jpeg
     - assets/images/iprogram1.jpeg
     - assets/images/iprogram2.jpeg
     - assets/images/iprogram3.jpeg
     - assets/images/tip1.jpeg
     - assets/images/tip2.png
     - assets/images/tip3.jpeg
     - assets/images/tip4.jpeg
     - assets/images/tip5.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: PatrickHand
       fonts:
          - asset: assets/fonts/Patrick_Hand/PatrickHand-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
